# Generated by Django 5.2 on 2025-06-04 06:42

import django.db.models.deletion
import documentos.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('es_publico', models.BooleanField(default=False)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.area')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=documentos.models.ruta_documento_personalizada)),
                ('version', models.PositiveIntegerField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='documentos.documento')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('documento', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ComentarioDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_publico', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.rol')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='documentos.documentoversion')),
            ],
        ),
        migrations.CreateModel(
            name='MetadatoPersonalizado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=255)),
                ('tipo_dato', models.CharField(choices=[('texto', 'Texto'), ('fecha', 'Fecha'), ('opcion', 'Opción múltiple')], default='texto', max_length=10)),
                ('opciones', models.JSONField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadatos', to='documentos.documento')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(default=True)),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_comentar', models.BooleanField(default=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='documentos.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('documento', 'usuario')},
            },
        ),
    ]
