# Generated by Django 5.2 on 2025-06-04 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('usuarios', '0003_rol_organizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='usuarios.organizacion'),
        ),
    ]
