# Generated by Django 5.2 on 2025-05-03 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoversion',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='documentoversion',
            name='subido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metadatopersonalizado',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadatos', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='permisodocumento',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='permisodocumento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.tipodocumento'),
        ),
        migrations.AlterUniqueTogether(
            name='documentoversion',
            unique_together={('documento', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='permisodocumento',
            unique_together={('documento', 'usuario')},
        ),
    ]
