# Generated by Django 5.2 on 2025-05-04 16:41

import documentos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisodocumento',
            name='puede_comentar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documento',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentoversion',
            name='archivo',
            field=models.FileField(upload_to=documentos.models.ruta_documento_personalizada),
        ),
    ]
