# Generated by Django 5.2 on 2025-05-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_remove_documentoversion_comentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatopersonalizado',
            name='opciones',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadatopersonalizado',
            name='tipo_dato',
            field=models.CharField(choices=[('texto', 'Texto'), ('fecha', 'Fecha'), ('opcion', 'Opción múltiple')], default='texto', max_length=10),
        ),
    ]
