# Generated by Django 5.2 on 2025-05-26 04:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_metadatopersonalizado_opciones_and_more'),
        ('usuarios', '0002_rolusuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatopersonalizado',
            name='id',
            field=models.BigAutoField(primary_key=True),
        ),
    ]
