# Generated by Django 5.2 on 2025-05-26 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_comentariodocumento_es_publico_and_more'),
        ('usuarios', '0002_rolusuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatopersonalizado',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
