# Generated by Django 5.2 on 2025-06-04 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlujoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujos', to='documentos.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpmnId', models.CharField(default='', max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('INICIO', 'Evento de inicio'), ('FIN', 'Evento de fin'), ('TAREA', 'Tarea manual'), ('DECISION', 'Decisión si/no')], max_length=10)),
                ('orden', models.PositiveIntegerField()),
                ('condicion', models.CharField(blank=True, max_length=255)),
                ('x', models.PositiveIntegerField(blank=True, null=True)),
                ('y', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('asignado_a_rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.rol')),
                ('asignado_a_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('flujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='workflows.flujotrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='TransicionFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(blank=True, max_length=255)),
                ('bpmnId', models.CharField(default='', max_length=255, unique=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones_entrada', to='workflows.elementoflujo')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones_salida', to='workflows.elementoflujo')),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(blank=True, null=True)),
                ('y', models.PositiveIntegerField(blank=True, null=True)),
                ('transicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='workflows.transicionflujo')),
            ],
        ),
    ]
