# Generated by Django 5.2 on 2025-05-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(blank=True, null=True)),
                ('y', models.PositiveIntegerField(blank=True, null=True)),
                ('transicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='workflows.transicionflujo')),
            ],
        ),
    ]
