# Generated by Django 5.2 on 2025-05-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_elementoflujo_bpmnid_elementoflujo_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementoflujo',
            name='bpmnId',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='elementoflujo',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementoflujo',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementoflujo',
            name='x',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementoflujo',
            name='y',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transicionflujo',
            name='bpmnId',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
