# Generated by Django 5.2 on 2025-06-04 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_es_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='usuarios.organizacion'),
        ),
    ]
