# Generated by Django 5.2.3 on 2025-06-22 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('evento', models.CharField(choices=[('formulario_completado', 'Formulario completado'), ('documento_cargado', 'Documento cargado'), ('estado_actualizado', 'Cambio de estado')], max_length=50)),
                ('condicion', models.JSONField(help_text="Ej: {'tipo_documento': 'contrato'}")),
                ('accion', models.CharField(choices=[('notificar', 'Enviar notificación'), ('cambiar_estado', 'Actualizar estado del documento'), ('activar_workflow', 'Activar flujo de trabajo'), ('actualizar_campo', 'Actualizar campo del documento')], max_length=50)),
                ('parametros_accion', models.JSONField(help_text="Ej: {'nuevo_estado': 'validado'}")),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EjecucionRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('exito', 'Éxito'), ('error', 'Error')], max_length=10)),
                ('mensaje', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_ejecutadas', to=settings.AUTH_USER_MODEL)),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglas.reglaautomatica')),
            ],
        ),
    ]
